# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=main
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),main)
  spy_config = main

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := spy

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

spy:
ifneq (,$(spy_config))
	@echo "==== Building spy ($(spy_config)) ===="
	@${MAKE} --no-print-directory -C . -f spy.make config=$(spy_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f spy.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  main"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   spy"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"